import jsPDF from 'jspdf';

const gradeColors = {
  'A+': [34, 197, 94], 'A': [74, 222, 128], 'B': [134, 239, 172],
  'C': [251, 191, 36], 'D': [249, 115, 22], 'F': [239, 68, 68]
};

export const downloadPDF = (analysis) => {
  const doc = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  let y = 0;

  // ---- Header ----
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageW, 40, 'F');

  doc.setTextColor(34, 197, 94);
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('Green Code Optimizer', 15, 20);   // ✅ removed emoji

  doc.setTextColor(156, 163, 175);
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(`Analysis Report -- ${new Date().toLocaleDateString()}`, 15, 30); // ✅ -- instead of —

  y = 55;

  // ---- Score circle ----
  const [r, g, b] = gradeColors[analysis.grade] || [34, 197, 94];
  doc.setFillColor(r, g, b);
  doc.circle(40, y + 10, 18, 'F');
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text(String(analysis.overallScore), 40, y + 15, { align: 'center' });

  doc.setTextColor(50, 50, 50);
  doc.setFontSize(14);
  doc.text(`Grade: ${analysis.grade}`, 70, y + 8);
  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  // ✅ CO2 instead of CO₂
  doc.text(`CO2 per run: ${analysis.totalCo2.toFixed(4)} g`, 70, y + 16);
  doc.text(`Files analyzed: ${analysis.files.length}`, 70, y + 23);

  y += 45;

  // ---- Summary ----
  doc.setFillColor(240, 253, 244);
  doc.rect(10, y, pageW - 20, 20, 'F');
  doc.setTextColor(15, 118, 110);
  doc.setFontSize(10);
  doc.text(analysis.summary || '', 15, y + 7, { maxWidth: pageW - 30 });
  y += 30;

  // ---- Recommendations ----
  doc.setTextColor(30, 30, 30);
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.text('Top Recommendations', 15, y);
  y += 8;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  (analysis.recommendations || []).forEach((rec, i) => {
    // ✅ clean text, no special chars
    const cleanRec = rec.replace(/[^\x00-\x7F]/g, '');
    doc.text(`${i + 1}. ${cleanRec}`, 15, y, { maxWidth: pageW - 30 });
    y += 10;
  });

  y += 5;

  // ---- Per-file breakdown ----
  doc.setFontSize(13);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(30, 30, 30);
  doc.text('File-by-File Analysis', 15, y);
  y += 8;

  analysis.files.forEach(file => {
    if (y > 260) { doc.addPage(); y = 20; }

    // File header bar
    doc.setFillColor(248, 250, 252);
    doc.rect(10, y - 2, pageW - 20, 22, 'F');

    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(30, 30, 30);
    doc.text(file.filename.split('/').pop(), 14, y + 5);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(80, 80, 80);
    // ✅ CO2 not CO₂, pipe | separator
    doc.text(
      `Score: ${file.greenScore}/100  |  Language: ${file.language}  |  Issues: ${file.issues?.length || 0}  |  CO2: ${file.co2Estimate < 0.01
        ? file.co2Estimate?.toFixed(6)
        : file.co2Estimate?.toFixed(4)}g`,
      14, y + 13
    );

    y += 28;

    // Issues list
    (file.issues || []).slice(0, 5).forEach(issue => {
      if (y > 270) { doc.addPage(); y = 20; }

      const sColor = {
        critical: [239, 68, 68],
        warning: [249, 115, 22],
        info: [59, 130, 246]
      };
      const [ir, ig, ib] = sColor[issue.severity] || [59, 130, 246];

      doc.setTextColor(ir, ig, ib);
      doc.setFontSize(8);
      doc.setFont('helvetica', 'bold');
      // ✅ no arrow symbol, use plain text
      doc.text(
        `[${issue.severity.toUpperCase()}] Line ${issue.lineStart}: ${issue.type}`,
        18, y
      );

      doc.setTextColor(80, 80, 80);
      doc.setFont('helvetica', 'normal');
      // ✅ strip non-ASCII from suggestion
      const cleanSuggestion = (issue.suggestion || '').replace(/[^\x00-\x7F]/g, '');
      doc.text(`Fix: ${cleanSuggestion}`, 22, y + 5, { maxWidth: pageW - 40 });
      y += 14;
    });

    y += 5;
  });

  // ---- Footer ----
  const lastPage = doc.internal.getNumberOfPages();
  doc.setPage(lastPage);
  doc.setFontSize(8);
  doc.setTextColor(156, 163, 175);
  doc.text(
    'Generated by Green Code Optimizer | Reduce Code Carbon Footprint',
    pageW / 2, 290,
    { align: 'center' }
  );

  doc.save(`green-report-${(analysis.projectName || 'report').replace(/\s/g, '-')}.pdf`);
};